# Generated by Django 5.0.1 on 2024-02-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_data_loaded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('zone', models.CharField(choices=[('North Central', 'North Central'), ('North East', 'North East'), ('North West', 'North West'), ('South East', 'South East'), ('South South', 'South South'), ('South West', 'South West')], max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGovernment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nigerian_states.state')),
            ],
        ),
    ]
