name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install black pytest pytest-cov

    - name: Run Black
      run: black .

    - name: Run tests
      run: pytest

    - name: Push changes
      if: success()
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto-formated code with Black and ran tests"
        commit_user_name: GitHub Actions
        commit_user_email: actions@github.com
        branch: ${{ github.ref }}
        commit_author: GitHub Actions <actions@github.com>