name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Specify the desired Node.js version here

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Black code formatter
      run: black .

    - name: Run tests
      run: pytest

    - name: Notify on success
      if: ${{ failure() == false }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.NIGERIAN_STATES_GITHUB_TOKEN }}
        script: |
          github.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: 'All Tests passed successfully. CI/CD build is successful.'
          })

    - name: Notify on failure
      if: ${{ failure() }}
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.NIGERIAN_STATES_GITHUB_TOKEN }}
        script: |
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'CI/CD Build Failed',
            body: 'The CI/CD build failed. Please check the build logs for more details.'
          })
